// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bncbbrmetwvmntewrfst.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJuY2Jicm1ldHd2bW50ZXdyZnN0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY2ODUxNzYsImV4cCI6MjA3MjI2MTE3Nn0.l6WRoor0IcgqULSYgs3EUP1QeCoWd2iiB4Qc8FrraYk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});